export const options = [
	{
		cat: "AmEx",
		name: "Platinum Travel",
		per: 50,
		points: 1,
		miles: 0.5,
		img: "/images/amex-pt.avif",
		accelerator: 3,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "Reward Multiplier",
		additionalInfo: "",
		desc: "Welcome Gift of <b>10,000</b> Membership Rewards points* redeemable for Flipkart voucher or Pay with Points option in Amex Travel Online worth <b>Rs. 3,000</b>. Effective from 22nd January, 2021.",
		fee: "First year fee: <b>Rs. 3,500</b> plus applicable taxes. <br />Second year onwards: <b>Rs. 5,000</b> plus applicable taxes.",
		rewardInfo: [
			"Earn 1 Membership Rewards® Point for every Rs. 50 spent except for spend on Fuel, Insurance, Utilities, Cash Transactions and EMI conversion at Point of Sale.",
			"Earn 3 Membership Rewards® Points for every Rs. 50 spent through American Express Reward Multiplier.",
		],
		milestoneInfo: [
			"Spend Rs. 15,000 within 90 days of Cardmembership entitles you to a Welcome Gift of 10,000 Membership Rewards points.",
			"On spending Rs. 1.90 Lacs in a year, earn 15,000 Membership Rewards points.",
			"On spending Rs. 4 Lacs in a year, earn 25,000 Membership Reward points.",
			"Spend Rs. 4 Lacs in a Cardmembership year and get a Taj Stay voucher worth Rs. 10,000 from Taj, SeleQtions and Vivanta Hotels",
		],
		referralLink:
			"https://americanexpress.com/en-in/referral/platinum-travel?ref=jEROMFjKyA&CPID=100505910",
		siteLink:
			"https://www.americanexpress.com/in/credit-cards/platinum-travel-credit-card/",
	},
	{
		cat: "AmEx",
		name: "Membership Rewards",
		per: 50,
		points: 1,
		miles: 0.5,
		img: "/images/mrcc.avif",
		accelerator: 2,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "Reward Multiplier",
		additionalInfo: "",
		desc: "Welcome Gift of <b>4,000</b> Bonus Membership Rewards Points",
		fee: "First year fee: <b>Rs. 1,000</b> plus applicable taxes. <br />Second year onwards: <b>Rs. 4,500</b> plus applicable taxes. (100% waived off on spend of Rs. 1.50 Lakhs in preceding year, else 50% waived off on spend of Rs. 90K - Rs. 1.49 Lakhs in preceding year)",
		rewardInfo: [
			"Earn 1 Membership Rewards® Point for every Rs. 50 spent except for spend on Fuel, Insurance, Utilities, Cash Transactions and EMI conversion at Point of Sale.",
			"Earn 2 Membership Rewards® Points for every Rs. 50 spent through American Express Reward Multiplier.",
		],
		milestoneInfo: [
			"Earn 1,000 Bonus Membership Rewards Points for simply using your card 4 times on transactions of Rs. 1,500 or above in a calendar month.",
			"Earn an additional 1,000 Membership Rewards points simply by spending INR 20,000 or more in a calendar month.",
			"Earn 5,000 Membership Rewards Points upon First Year Card Renewal, on payment of annual membership fee.",
		],
		siteLink:
			"https://www.americanexpress.com/in/credit-cards/membership-rewards-card/",
	},
	{
		cat: "Axis",
		name: "ACE",
		per: 100,
		points: 1.5,
		miles: 1,
		img: "/images/ace.jpg",
		accelerator: 5 / 1.5,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "GPay",
		additionalInfo:
			"5% cashback on bill payments (electricity, internet, gas, and more) & DTH and mobile recharges on Google Pay",
		desc: "Zero joining fee for select channels",
		fee: "First year fee: <b>Rs. 499</b> plus applicable taxes. (Rs. 0 for select channels) <br />Second year onwards: <b>Rs. 499</b> plus applicable taxes (waived off on spend of Rs. 2 Lakhs in preceding year.  Rent transactions and wallet load transactions will not be eligible for spends counted in availing annual fee waiver.)",
		rewardInfo: [
			"5% cashback on bill payments (electricity, internet, gas, and more) &DTH and mobile recharges on Google Pay",
			"4% cashback on Swiggy, Zomato &amp; Ola",
			"1.5% cashback on all other spends",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.axisbank.com/retail/cards/credit-card/axis-bank-ace-credit-card",
	},
	{
		cat: "Axis",
		name: "Atlas",
		per: 100,
		points: 2,
		miles: 2,
		img: "/images/atlas.png",
		accelerator: 2.5,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "Travel Bookings",
		additionalInfo: "Spends on Travel EDGE, airline and hotel merchants",
		desc: "<b>2500 EDGE Miles</b> as welcome benefit upon first transaction on your ATLAS credit card within 37 days from the date of card issuance.",
		fee: "First year fee: <b>Rs. 5,000</b> plus applicable taxes. <br />Second year onwards: <b>Rs. 5,000</b> plus applicable taxes.",
		rewardInfo: [
			"Earn 2 EDGE Miles for every Rs. 100 spent except for spends on gold/jewellery, rent, wallet, government institution, insurance, fuel and utilities.",
			"Earn 5 EDGE Miles for every 100 spent on Travel EDGE, airline and hotel merchants up to cumulative transactions of Rs. 2,00,000 per month.",
		],
		milestoneInfo: [
			"On spending Rs. 3 Lacs in a year, earn 2,500 EDGE Miles.",
			"On spending Rs. 7.5 Lacs in a year, earn additional 2,500 EDGE Miles.",
			"On spending Rs. 15 Lacs in a year, earn additional 5,000 EDGE Miles.",
		],
		siteLink:
			"https://www.axisbank.com/retail/cards/credit-card/axis-bank-atlas-credit-card",
	},
	{
		cat: "Axis",
		name: "Magnus",
		per: 200,
		points: 12,
		miles: 2 / 5,
		img: "/images/magnus.png",
		accelerator: 5,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "TravelEdge",
		additionalInfo: "",
		desc: "Complimentary luxury brand voucher worth Rs. 12,500",
		fee: "First year fee: <b>Rs. 12,500</b> plus applicable taxes. <br />Second year onwards: <b>Rs. 12,500</b> plus applicable taxes (waived off on spend of Rs. 25 Lakhs in preceding year)",
		rewardInfo: [
			"Earn 12 eDGE Reward points per Rs. 200 on spends up to Rs. 1.50 Lakhs and 35 eDGE Reward points per Rs. 200 on incremental spends above Rs. 1.50 lakhs in a calendar month.",
			"5X Reward points on spends via Travel eDGE.",
			"Earn 2 partner miles for every 5 eDGE Reward points across 20 travel partners.",
			"Wallet Transactions, Government Institutions and Utilities will not be eligible for edge reward points and spends done on these categories will not be considered for base eDGE rewards and accelerated eDGE rewards threshold calculation on Rs. 1,50,000. In addition this, Insurance, Fuel and Gold &amp; Jewellery will not be eligible to earn base eDGE rewards points and accelerated reward points.",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.axisbank.com/retail/cards/credit-card/axis-bank-magnus-card/feature-benefits",
	},
	{
		cat: "HDFC",
		name: "Infinia Metal",
		per: 150,
		points: 5,
		miles: 1,
		img: "/images/infinia.png",
		accelerator: 5,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "SmartBuy",
		additionalInfo: "5x",
		desc: "Enjoy Welcome and Renewal benefit of 12,500 reward points upon fee realisation and card activation",
		fee: "Joining/Renewal Membership Fee – <b>Rs. 12,500</b> plus applicable taxes. <br />Spend 10 lakhs or more in the preceding 12 months and get renewal membership fee waived off for next year.",
		rewardInfo: [
			"Earn 5 Reward Points on every Rs. 150 retail spends including Insurance, Utilities and Education​",
			"Earn up to 10 times Reward Points on your travel and shopping spends on Smartbuy",
			"Redeem Flight and Hotel Bookings via Smartbuy at a value of 1 RP = Rs. 1",
			"Redeem Apple products and Tanishq vouchers via Smartbuy at a value of 1RP = Rs. 1",
			"Redeem Airmiles conversion through netbanking at a value of 1RP = 1 airmile",
			"Redeem Products and Vouchers via Netbanking or SmartBuy at a value of 1 RP = upto Rs. 0.50",
			"Redeem Cashback at a value of 1 RP = Rs. 0.30",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.hdfcbank.com/personal/pay/cards/credit-cards/infinia-credit-card",
	},
	{
		cat: "HDFC",
		name: "Millennia",
		per: 100,
		points: 1,
		miles: 1,
		img: "/images/millennia.png",
		accelerator: 5,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "Specific Merchants",
		additionalInfo:
			"Amazon, BookMyShow, Cult.fit, Flipkart, Myntra, Sony LIV, Swiggy, Tata CLiQ, Uber and Zomato",
		desc: "Pay your Membership fee and get Reward Points equivalent to Fee Amount",
		fee: "Joining/Renewal Membership Fee – <b>Rs. 1,000</b> plus applicable taxes. <br />Spend ₹1 lakh or more in the preceding 12 months and get renewal membership fee waived off for next year.",
		rewardInfo: [
			"5% Cashback on Amazon, BookMyShow, Cult.fit, Flipkart, Myntra, Sony LIV, Swiggy, Tata CLiQ, Uber and Zomato",
			"1% cashback on all other spends (except Fuel, Wallet, EMI, Govt transactions)",
			"₹1000 worth gift vouchers on spends of ₹1,00,000 and above in each calendar quarter",
			"CashBack will be given in the form of CashPoints, which can be redeemed by you against the statement balance.",
			"The redemption against the statement balance will be at the rate of 1 CashPoint = ₹1",
			"CashPoints can also be used for redemption against travel benefits like Flight & Hotel bookings and Rewards Catalogue at the SmartBuy Rewards Portal, at a value of 1 CashPoint = ₹0.30.",
			"Redeem CashPoints at the conversion rate of 1 CashPoint = ₹0.30",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.hdfcbank.com/personal/pay/cards/millennia-cards/millennia-cc-new",
	},
	{
		cat: "HDFC",
		name: "Regalia Gold",
		per: 150,
		points: 4,
		miles: 0.5,
		img: "/images/regalia.png",
		accelerator: 5,
		isMiles: true,
		isCashback: false,
		isHotel: false,
		acceleratedType: "SmartBuy",
		additionalInfo: "",
		desc: "Complimentary Swiggy One and MMT Black Gold Membership when you spend Rs. 1 Lakhs and above within 90 days of card issuance",
		fee: "Joining/ Renewal Membership Fee of <b>Rs. 2500</b> plus applicable taxes. <br />Spend Rs. 4 Lakhs in an anniversary year (12 billing cycles) and get Renewal Fee waived for next renewal year.",
		rewardInfo: [
			"Earn 4 Reward Points on every Rs.150  retail* spends including Insurance, Utilities and Education​",
			"Earn 20 Reward Points on every Rs.150  retail* spends at Marks & Spencer, Myntra, Reliance Digital, Nykaa!",
			"Exclusive Gold Catalogue on select Premium brands via Smartbuy at a value of 1 RP = Rs 0.65",
			"Flights and hotel bookings via Smartbuy at a value of 1 RP = Rs 0.5",
			"Airmiles conversion through Netbanking or SmartBuy at a value of 1RP = upto 0.5 airmiles",
			"Products and Vouchers via Netbanking or SmartBuy at a value of 1 RP = upto Rs 0.35",
			"The redemption against the statement balance will be at the rate of 1 RP = Rs 0.20",
		],
		milestoneInfo: [
			"Get ₹ 1,500 worth vouchers from Marriott, Myntra, Marks & Spencer or Reliance Digital when you spend Rs. 1.5 Lakhs in every calendar quarter.",
			"Get ₹ 5,000 worth flight vouchers when you spend Rs. 5 Lakhs spends in an anniversary year.",
			"Get additional ₹ 5,000 worth flight vouchers when you spend Rs. 7.5 Lakhs spends in an anniversary year.",
		],
		siteLink:
			"https://www.hdfcbank.com/personal/pay/cards/credit-cards/regalia-gold-credit-card",
	},
	{
		cat: "ICICI",
		name: "Emeralde Private Metal",
		per: 200,
		points: 6,
		miles: 1,
		img: "/images/emeralde-private.png",
		accelerator: 1,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "N/A",
		additionalInfo: "",
		desc: "Complimentary Night Stay With Taj Epicure Membership",
		fee: "Joining/ Renewal Membership Fee of <b>Rs. 12,500</b> plus applicable taxes. <br />Spend Rs. 10 Lakhs in an anniversary year and get Renewal Fee waived for next renewal year.",
		rewardInfo: [
			"Get 12,500 ICICI Reward Points as Joining Bonus.",
			"Earn 6 ICICI Bank Reward Points for every Rs 200 spent on retail transactions, excluding Tax, Fuel, and Rent payments. Get the same rate for Grocery, Education, Utilities, and Insurance payments. Value of each Reward Point is upto Re 1.",
			"Grocery, Utilities, and Education: Max 1,000 Reward Points per category per statement cycle.",
			"Insurance payments: Max 5,000 Reward Points per category per statement cycle.",
		],
		milestoneInfo: [
			"Complimentary EaseMYTrip air travel Voucher worth Rs 6,000 {2 voucher(s) worth Rs 3,000 each} on annual spends. You will receive 1st EaseMYTrip voucher on spending Rs 4 lakh and 2nd EaseMyTrip voucher on reaching spends of Rs 8 lakh in an anniversary year.",
			"Get 12,500 ICICI Reward Points as Annual Bonus",
		],
		siteLink:
			"https://www.icicibank.com/personal-banking/cards/credit-card/emeralde-private-metal-credit-card",
	},
	{
		cat: "ICICI",
		name: "Adani one Signature",
		per: 100,
		points: 1.5,
		miles: 1,
		img: "/images/adani-sign.webp",
		accelerator: 7 / 1.5,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "Adani One ecosystem",
		additionalInfo:
			"Adani managed Airports, Trainman, Gas, Electricity and more",
		desc: "<b>₹5,000</b> Flight Ticket Voucher",
		fee: "Joining/ Renewal Membership Fee of <b>Rs. 5,000</b> plus applicable taxes. <br />Spend Rs. 6 Lakhs in an anniversary year and get Renewal Fee waived for next renewal year.",
		rewardInfo: [
			"7% on Adani One (flights, hotels, trains, etc.), Airports, (F&B, Retail, etc.), Trainman, Gas, Electricity and more",
			"Enjoy 2% Adani Reward Points on international spends",
			"Get flat 1.5% Adani Reward Points on all spends, except for fuel, rent, or any other listed categories as a part of MITC of credit cards issued by ICICI Bank",
			"One Adani Reward Point is equal to ₹1. You can redeem 100% of your collected Adani Reward Points on any transaction.",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.adanione.com/adani-one-icici-bank-credit-cards/signature-card-features",
	},
	{
		cat: "SBI",
		name: "Cashback",
		per: 100,
		points: 1,
		miles: 1,
		img: "/images/sbicashback.png",
		accelerator: 5,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "Online Merchants",
		additionalInfo:
			"Not applicable on Merchant EMI & Flexipay EMI transactions and on following categories: Utility, Insurance, Fuel, Rent, Wallet, School & Educational Services, Jewelry, Railways etc.",
		desc: "Card Cashback gets auto-credited to your SBI Card account within two days of your next statement generation",
		fee: "Joining Fee: <b>Rs. 999</b> plus applicable taxes. <br />Renewal Fee (Per Annum): <b>Rs. 999</b> plus applicable taxes from second year onwards (waived off on spend of Rs. 2 Lakhs in preceding year)",
		rewardInfo: [
			"5% Cashback on online* spends without any merchant restriction",
			"1% Cashback on offline* spends",
			"Cashback not applicable on Merchant EMI & Flexipay EMI transactions and on following categories: Utility, Insurance, Fuel, Rent, Wallet, School & Educational Services, Jewelry, Railways etc.",
		],
		milestoneInfo: [],
		siteLink:
			"https://www.sbicard.com/en/personal/credit-cards/rewards/cashback-sbi-card.page",
	},
	{
		cat: "SBI",
		name: "Elite",
		per: 100,
		points: 2,
		miles: 0.25,
		img: "/images/sbielite.png",
		accelerator: 5,
		isMiles: false,
		isCashback: true,
		isHotel: false,
		acceleratedType: "Specific Merchants",
		additionalInfo: "Dining, Departmental stores and Grocery Spends",
		desc: "Welcome e-Gift Voucher worth Rs. 5,000",
		fee: "Joining Fee: <b>Rs. 4,999</b> plus applicable taxes. <br />Renewal Fee (Per Annum): <b>Rs. 4,999</b> plus applicable taxes from second year onwards (waived off on spend of Rs. 10 Lakhs in preceding year)",
		rewardInfo: [
			"Get 5X Reward Points on Dining, Departmental stores and Grocery Spends",
			"Earn 2 Reward Points per Rs. 100 on all other spends, except fuel",
		],
		milestoneInfo: [
			"Earn upto 50,000 Bonus Reward Points worth Rs. 12,500/ year",
			"Earn 10,000 bonus Reward Points on achieving annual spends of Rs. 3 lakhs and 4 lakhs",
			"Earn 15,000 bonus Reward Points on achieving annual spends of Rs. 5 lakhs and 8 lakhs",
		],
		siteLink:
			"https://www.sbicard.com/en/personal/credit-cards/lifestyle/sbi-card-elite.page",
	},
	// {
	//   cat: "",
	//   name: "",
	//   per: 1,
	//   points: 1,
	//   miles: 0,
	//   img: "/images/.png",
	//   accelerator: 5,
	//   isMiles: false,
	//   isCashback: true,
	//   isHotel: false,
	//   acceleratedType: "",
	//   additionalInfo: "",
	//   desc: "",
	//   fee: "",
	//   rewardInfo: [],
	//   milestoneInfo: [],
	//   siteLink: "",
	// },
];
