export const options = [
  //   {
  //     cat: "American Express",
  //     name: "MRCC",
  //     per: 100,
  //     points: 1,
  //     miles: 0.5,
  //   },
  {
    cat: "AmEx",
    name: "Platinum Travel",
    per: 50,
    points: 1,
    miles: 0.5,
    img: "/images/amex-pt.avif",
    accelerator: 3,
    isMiles: true,
    isCashback: false,
    isHotel: false,
    acceleratedType: "Reward Multiplier",
  },
  {
    cat: "Axis",
    name: "Atlas",
    per: 100,
    points: 2,
    miles: 2,
    img: "/images/atlas.png",
    accelerator: 2.5,
    isMiles: true,
    isCashback: false,
    isHotel: false,
    acceleratedType: "TravelEdge",
  },
  {
    cat: "Axis",
    name: "Magnus",
    per: 200,
    points: 12,
    miles: 2 / 5,
    img: "/images/magnus.png",
    accelerator: 5,
    isMiles: true,
    isCashback: false,
    isHotel: false,
    acceleratedType: "TravelEdge",
  },
  {
    cat: "HDFC",
    name: "Infinia",
    per: 150,
    points: 5,
    miles: 1,
    img: "/images/infinia.png",
    accelerator: 5,
    isMiles: true,
    isCashback: false,
    isHotel: false,
    acceleratedType: "SmartBuy",
  },
  {
    cat: "HDFC",
    name: "Millennia",
    per: 100,
    points: 1,
    miles: 1,
    img: "/images/millennia.png",
    accelerator: 5,
    isMiles: false,
    isCashback: true,
    isHotel: false,
    acceleratedType: "Specific Merchants",
  },
  {
    cat: "HDFC",
    name: "Regalia Gold",
    per: 150,
    points: 4,
    miles: 0.5,
    img: "/images/regalia.png",
    accelerator: 5,
    isMiles: true,
    isCashback: false,
    isHotel: false,
    acceleratedType: "SmartBuy",
  },
  {
    cat: "SBI",
    name: "Cashback",
    per: 100,
    points: 1,
    miles: 1,
    img: "/images/sbicashback.png",
    accelerator: 5,
    isMiles: false,
    isCashback: true,
    isHotel: false,
    acceleratedType: "Specific Merchants",
    additionalInfo: "hellooooo",
  },
  //   {
  //     cat: "SBI",
  //     name: "Elite",
  //     per: 100,
  //     points: 1,
  //     miles: 0,
  //   },
];
